[theme]
primaryColor = "#FFC107"          # Amarelo (Botões e Sliders)
backgroundColor = "#0A0A0A"       # Preto Profundo (Fundo da página)
secondaryBackgroundColor = "#1A1A1A" # Cinza Escuro (Barra lateral e Cards)
textColor = "#E0E0E0"             # Branco Suave (Texto para não cansar a vista)
font = "sans serif"               # Fonte Limpa

[server]
runOnSave = true
